### PR TITLE
Capitalization support

### LINKED ISSUE #11: Fix swedish letters
In consonant(letter) the swedishs letters dont seem to work, probably a unicode issue.

### PR DESCRIPTION
**Pull request by lindwaltz**
Adds support for detecting Capitalization of words. Also fixes #11 and a bug when translating consonant-only words.

### CODE REVIEW

**Comment by lindwaltz** [comment]
note that python 2.x is unicode hell, switch to python 3 !

**Comment by ghost** [comment]
Thanks for your contribution. :+1:

**Comment by laperss** [comment]
A request for switching python version will be put forward to the SCRUM master

**Comment by ghost** [comment]
Already fixed!

**Pull request merged**
